// Code generated by "stringer -type=Activity -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActUnknown-0]
	_ = x[ActWrite-1]
	_ = x[ActDelete-2]
	_ = x[ActSnapshot-3]
}

const _Activity_name = "writedeletesnapshot"

var _Activity_index = [...]uint8{0, 0, 5, 11, 19}

func (i Activity) String() string {
	if i >= Activity(len(_Activity_index)-1) {
		return "Activity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Activity_name[_Activity_index[i]:_Activity_index[i+1]]
}
