// Code generated by "stringer -type=ChangeAction -linecomment"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CAUnknown-0]
	_ = x[CACreate-1]
	_ = x[CADelete-2]
	_ = x[CAMove-3]
	_ = x[CAUpdate-4]
}

const _ChangeAction_name = "\"\"\"Create\"\"Delete\"\"Move\"\"Update\""

var _ChangeAction_index = [...]uint8{0, 2, 10, 18, 24, 32}

func (i ChangeAction) String() string {
	if i >= ChangeAction(len(_ChangeAction_index)-1) {
		return "ChangeAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChangeAction_name[_ChangeAction_index[i]:_ChangeAction_index[i+1]]
}
